apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app1: netcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app1: netcore
  template:
    metadata:
      labels:
        app1: netcore
        app: {{ template "gateway.name" . }}
        draft: {{ default "draft-app" .Values.draft }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID | quote }}
    spec:
      containers:
      - name: mycontainer
        image: foodyhiveacr.azurecr.io/komirisettyazuremaintest:default
        imagePullPolicy: Always
